name: Push Queries to Dune

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "queries/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4

      - uses: extractions/setup-just@v2
        with:
          just-version: 1.40.0

      - name: Define a cache for the virtual environment based on the lock file
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Regenerate lock file if needed
        run: |
          poetry lock --check || poetry lock

      - name: Install the project dependencies
        run: poetry install

      - name: Lint the Python code
        run: just lint

      - name: Lint the SQL code
        run: poetry run sqlfluff lint ./queries/*.sql

      - name: Log directory structure
        run: |
          pwd
          ls -R

      - name: Update all queries on Dune
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
        run: poetry run python -u scripts/push_to_dune.py

      - name: "Summary"
        run: |
          echo "## Push to Dune result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Pushed" >> $GITHUB_STEP_SUMMARY
